server.port=8085
spring.application.name=service-batch

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_batch
spring.datasource.username=postgres
spring.datasource.password=20021227
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Actuator
management.endpoints.web.exposure.include=health,info