server.port=8084
spring.application.name=service-notifications

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_notifications
spring.datasource.username=postgres
spring.datasource.password=20021227
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Kafka Consumer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notifications-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Actuator
management.endpoints.web.exposure.include=health,info